import type { Metadata } from "next";
import { Cormorant_Garamond, Playfair_Display, DM_Sans, Josefin_Sans} from "next/font/google";
import "./globals.css";
import Navbar from '@/components/layout/Navbar';
import SocialSidebar from "@/components/layout/SocialSidebar";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-cormorant",
  display: "swap",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  variable: "--font-dm-sans",
  display: "swap",
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  variable: "--font-josefin",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cormorant.variable} ${playfair.variable} ${dmSans.variable} ${josefin.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><Navbar /><SocialSidebar />{children}</body>
    </html>
  );
}
